### Criar novo pagamento
POST http://localhost:3000/payments
Content-Type: application/json

{
    "amount": 1000,
    "currency": "BRL",
    "paymentMethod": "pm_card_visa"
}


### Listar TODOS os pagamentos
GET http://localhost:3000/payments
Content-Type: : application/json

### Listar apenas pagamentos SUCEDIDOS
GET http://localhost:3000/payments?status=SUCCEEDED

### Listar apenas pagamentos PENDENTES
GET http://localhost:3000/payments?status=PENDING

### Listar apenas pagamentos FALHADOS
GET http://localhost:3000/payments?status=FAILED
