### Criar novo pagamento
POST http://localhost:3000/payments
Content-Type: application/json

{
    "amount": 1000,
    "currency": "BRL",
    "paymentMethod": "pm_card_visa"
}


### Listar TODOS os pagamentos
GET http://localhost:3000/payments
Content-Type: : application/json

### Listar apenas pagamentos SUCEDIDOS
GET http://localhost:3000/payments?status=SUCCEEDED

### Detalhes de um pagamento 
GET http://localhost:3000/payments/a695e68f-b75c-4b96-9e9d-4098d6b13e8f